version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - S3_BUCKET=mybucket
      - AWS_REGION=us-east-1
      - LOCALSTACK_HOSTNAME=localstack
    depends_on:
      - mongo
      - localstack
    command: npm start
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" # Gateway
      - "4572:4572" # S3
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "./localstack_data:/var/lib/localstack"

volumes:
  mongo_data:
  localstack_data:
