service: fullstack-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    MONGO_URI: mongodb://mongo:27017/mydatabase
    S3_BUCKET: mybucket

functions:
  generatePresignedUrl:
    handler: handler.generatePresignedUrl
    events:
      - http:
          path: upload-url
          method: post
  processOrders:
    handler: handler.processOrders
    events:
      - schedule:
          rate: rate(1 day)

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mybucket
